### PR TITLE
As press page html

### PR DESCRIPTION
**Pull request by alexsanchez728**
Hey friends! I'm 99% done with my press page but I'm having a prob,

My array is printing out an "undefined" to the domString object right before it prints all the stuff that I put in, and it's only printing it once, not each time the loop runs, I can't figure out where it's coming from or how to get rid of it. 😠 

see:

screen shot 2017-08-10 at 9 47 51 am

If you could test it out and see if you can fix it that'd be 👌

### CODE REVIEW

**Comment by jessibcoden** [comment]
Alex, try declaring domString with "". We did it on my machine and that seemed to work.

**Comment by alexsanchez728** [comment]
That did it!

**Comment by jessibcoden** [comment]
👍

**Comment by belv2c** [comment]
👍

**Comment by EHolman7** [comment]
👍

**Pull request merged**
