### PR TITLE
added product arrays

### PR DESCRIPTION
**Pull request by EHolman7**

### CODE REVIEW

**Comment by belv2c** [comment]
Let's get rid of the sold-out

**Comment by jessibcoden** [comment]
👎 
Omit Sold Out

**Comment by alexsanchez728** [comment]
please

**Comment by belv2c** [comment]
plz

**Comment by jessibcoden** [comment]
Please (cry baby)

**Comment by alexsanchez728** [comment]
pls

**Comment by jessibcoden** [comment]
👍

**Comment by alexsanchez728** [comment]
👍

**Comment by belv2c** [comment]
👍

**Pull request merged**
